# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: das-daemonless
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
      interpreter_python: auto_silent
  inventory:
    host_vars:
      das-daemonless:
        ansible_connection: local
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
